# [general]
import = [
    "~/.config/alacritty/linux.toml",

    # This is ignored if not found, overwrites linux if found. 
    "~/.config/alacritty/darwin.toml",
]

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[font]
builtin_box_drawing = true

[font.normal]
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window.padding]
x = 2
y = 2

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"
