#!/bin/bash

# Use the provided interface, otherwise the device used for the default route.
IF="${IFACE:-$BLOCK_INSTANCE}"
IF="${IF:-$(ip route | awk '/^default/ { print $5 ; exit }')}"

# Exit if there is no default route
[[ -z "$IF" ]] && exit

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

AF=${ADDRESS_FAMILY:-inet6?}
LABEL="${LABEL:-}"

for flag in "$1" "$2"; do
  case "$flag" in
    -4)
      AF=inet ;;
    -6)
      AF=inet6 ;;
    -L)
      if [[ "$IF" = "" ]]; then
        LABEL="iface"
      else
        LABEL="$IF:"
      fi ;;
  esac
done

if [[ "$IF" = "" ]] || [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo "${LABEL} down" # full text
  echo "${LABEL} down" # short text
  echo \#FF0000 # color
  exit
fi

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^ \/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

if [[ "${display_wifi_name}" == "1" ]];
then
  # try to guess the wifi name
  WIFI_NAME=$(nmcli -t -f active,ssid dev wifi | grep -E '^yes' | cut -d: -f2)
  message="$LABEL$WIFI_NAME ($IPADDR)"
else
  message="$LABEL$IPADDR"
fi

#------------------------------------------------------------------------

echo "$message"
echo "$LABEL$IPADDR"
