# Editor completions
"$schema" = "https://starship.rs/config-schema.json"

format = """
$all\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

# Newline between prompts
add_newline = false

[fill]
symbol = " "

# Enable kubernetes module
[kubernetes]
disabled = false

[aws]
disabled = true

[time]
disabled = false
style = "dimmed"
format = "[at $time]($style)"
